//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_sach_nhan_vien.xlsx.
        /// </summary>
        public static string EmployeeExcelFileName {
            get {
                return ResourceManager.GetString("EmployeeExcelFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode is not null.
        /// </summary>
        public static string EN_ValidateError_EmployeeCodeNotEmpty {
            get {
                return ResourceManager.GetString("EN_ValidateError_EmployeeCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã NV đã tồn tại, vui lòng nhập mã khác.
        /// </summary>
        public static string VN_ValidateError_EmployeeCodeDuplicate {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép lớn hơn 20 kí tự, vui lòng kiểm tra lại.
        /// </summary>
        public static string VN_ValidateError_EmployeeCodeIsNoMoreThan20 {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeCodeIsNoMoreThan20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã NV chưa tồn tại, vui lòng nhập đúng mã nv khác.
        /// </summary>
        public static string VN_ValidateError_EmployeeCodeNotDuplicate {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeCodeNotDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã NV không được phép để trống.
        /// </summary>
        public static string VN_ValidateError_EmployeeCodeNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được lớn hơn ngày hiện tại, vui lòng kiểm tra lại.
        /// </summary>
        public static string VN_ValidateError_EmployeeDOBNotValid {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeDOBNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email NV không được phép để trống.
        /// </summary>
        public static string VN_ValidateError_EmployeeEmailNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeEmailNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng, vui lòng kiểm tra lại.
        /// </summary>
        public static string VN_ValidateError_EmployeeEmailNotValid {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDT NV không được phép để trống.
        /// </summary>
        public static string VN_ValidateError_EmployeeMobileNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeMobileNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TênNV không được phép để trống.
        /// </summary>
        public static string VN_ValidateError_EmployeeNameNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeNameNotEmpty", resourceCulture);
            }
        }
    }
}
